_BASE_: "Base-Pretrain.yaml"
MODEL:
  WEIGHTS: "R-50.pkl"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn" 
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (160000, 220000)
  MAX_ITER: 260000
  CHECKPOINT_PERIOD: 500
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/batext/pretrain/attn_R_50"
